"""Named starting poses for the articulated engineering mannequin.

Angles are anatomical joint degrees in the neutral body axes. These are static
reference positions, not motion capture or balanced simulation states.
"""


def _both(**joints):
    return {f'{side}_{joint}': angle for side in ('left', 'right') for joint, angle in joints.items()}


def _sides(left=None, right=None, **torso):
    return {**{f'left_{joint}': angle for joint, angle in (left or {}).items()},
            **{f'right_{joint}': angle for joint, angle in (right or {}).items()}, **torso}


def _preset(label, group, description, angles=None, root_rotation_deg=None, ground=False):
    return {'label': label, 'group': group, 'description': description,
            'angles': angles or {}, 'root_rotation_deg': root_rotation_deg,
            'ground': ground}


HUMAN_POSES = {
    'standing': _preset('Standing neutral', 'Standing & gestures', 'Upright with arms relaxed at the sides.'),
    'at-ease': _preset('Standing at ease', 'Standing & gestures', 'Weight shared, hands slightly behind the hips.',
                       _both(shoulder=[-20, 0, 0], elbow=20, hip=[5, 0, 0], knee=-8)),
    'hands-up': _preset('Hands up', 'Standing & gestures', 'Both arms raised above the head with open elbows.',
                        _both(shoulder=[165, 0, 0], elbow=12)),
    'arms-forward': _preset('Arms forward', 'Standing & gestures', 'Both arms reaching straight forward at shoulder height.',
                            _both(shoulder=[90, 0, 0])),
    'arms-spread': _preset('Arms spread', 'Standing & gestures', 'Both arms extended sideways at shoulder height.',
                           _sides(left={'shoulder': [0, 0, -90]}, right={'shoulder': [0, 0, 90]})),
    'box-trapped': _preset('Trapped in a box', 'Standing & gestures', 'Palms forward and elbows bent as if pressing against walls.',
                           _sides(left={'shoulder': [75, 0, -40], 'elbow': 90, 'wrist': [35, 0, 0]},
                                  right={'shoulder': [75, 0, 40], 'elbow': 90, 'wrist': [35, 0, 0]})),
    'pointing': _preset('Pointing right', 'Standing & gestures', 'Right arm extended outward; left hand rests near the body.',
                        _sides(left={'elbow': 75}, right={'shoulder': [30, 0, 85]})),
    'wave': _preset('Waving', 'Standing & gestures', 'Right elbow raised and bent with the hand beside the head.',
                    _sides(right={'shoulder': [120, 0, 50], 'elbow': 100, 'wrist': [20, 0, 0]})),
    'carry': _preset('Carrying at waist', 'Standing & gestures', 'Forearms bent forward to support an object at waist height.',
                     _both(shoulder=[35, 0, 0], elbow=100, wrist=[-20, 0, 0])),
    'star-jump': _preset('Star jump', 'Standing & gestures', 'Arms and legs spread into a broad X shape.',
                         _sides(left={'shoulder': [145, 0, -45], 'hip': [0, 30, 0]},
                                right={'shoulder': [145, 0, 45], 'hip': [0, -30, 0]})),
    'walk-left': _preset('Walking · left leg forward', 'Movement', 'Left step forward with opposing arm swing.',
                         _sides(left={'hip': [35, 0, 0], 'knee': -12, 'shoulder': [-25, 0, 0]},
                                right={'hip': [-18, 0, 0], 'knee': -30, 'shoulder': [35, 0, 0], 'elbow': 20})),
    'walk-right': _preset('Walking · right leg forward', 'Movement', 'Right step forward with opposing arm swing.',
                          _sides(left={'hip': [-18, 0, 0], 'knee': -30, 'shoulder': [35, 0, 0], 'elbow': 20},
                                 right={'hip': [35, 0, 0], 'knee': -12, 'shoulder': [-25, 0, 0]})),
    'running': _preset('Running stride', 'Movement', 'Long left stride, bent elbows and an active opposite arm swing.',
                       _sides(left={'hip': [65, 0, 0], 'knee': -48, 'shoulder': [-45, 0, 0], 'elbow': 85},
                              right={'hip': [-20, 0, 0], 'knee': -95, 'shoulder': [80, 0, 0], 'elbow': 90},
                              lumbar_flex=[12, 0, 0])),
    'sprint-start': _preset('Sprint start', 'Movement', 'Deep forward lean with one knee driving ahead.',
                            _sides(left={'hip': [100, 0, 0], 'knee': -110, 'shoulder': [85, 0, 0], 'elbow': 80},
                                   right={'hip': [10, 0, 0], 'knee': -70, 'shoulder': [-35, 0, 0], 'elbow': 95},
                                   lumbar_flex=[35, 0, 0], thoracic_flex=[15, 0, 0])),
    'step-up': _preset('Stepping up', 'Movement', 'Right knee lifted toward a step, arms balancing.',
                       _sides(left={'hip': [5, 0, 0], 'knee': -8, 'shoulder': [55, 0, -20]},
                              right={'hip': [85, 0, 0], 'knee': -90, 'shoulder': [-25, 0, 20]})),
    'lunge-left': _preset('Lunge · left foot forward', 'Movement', 'Left leg forward and bent; right leg trailing.',
                          _sides(left={'hip': [75, 0, 0], 'knee': -95}, right={'hip': [-20, 0, 0], 'knee': -20},
                                 lumbar_flex=[12, 0, 0])),
    'lunge-right': _preset('Lunge · right foot forward', 'Movement', 'Right leg forward and bent; left leg trailing.',
                           _sides(left={'hip': [-20, 0, 0], 'knee': -20}, right={'hip': [75, 0, 0], 'knee': -95},
                                  lumbar_flex=[12, 0, 0])),
    'seated': _preset('Seated', 'Sitting & equipment', 'Upright on a chair-height seat, knees at right angles.',
                      _both(hip=[90, 0, 0], knee=-90, elbow=80)),
    'seated-arms-spread': _preset('Seated · arms spread', 'Sitting & equipment', 'Chair-height seat with both arms extended sideways.',
                                  {**_both(hip=[90, 0, 0], knee=-90),
                                   **_sides(left={'shoulder': [0, 0, -90]}, right={'shoulder': [0, 0, 90]})}),
    'seated-hands-up': _preset('Seated · hands up', 'Sitting & equipment', 'Chair-height seat with hands raised overhead.',
                               _both(hip=[90, 0, 0], knee=-90, shoulder=[160, 0, 0], elbow=20)),
    'seated-reach': _preset('Seated · forward reach', 'Sitting & equipment', 'Lean over the thighs with arms reaching forward.',
                            {**_both(hip=[90, 0, 0], knee=-90, shoulder=[95, 0, 0]),
                             'lumbar_flex': [30, 0, 0], 'thoracic_flex': [15, 0, 0]}),
    'rowing-catch': _preset('Rowing · catch', 'Sitting & equipment', 'Knees folded, torso forward and arms reaching for a handle.',
                             {**_both(hip=[105, 0, 0], knee=-120, shoulder=[100, 0, 0]),
                              'lumbar_flex': [30, 0, 0]}),
    'rowing-pull': _preset('Rowing · pull', 'Sitting & equipment', 'Legs extended, torso back and elbows pulling beside the ribs.',
                            _both(hip=[80, 0, 0], knee=-25, shoulder=[30, 0, 0], elbow=120)),
    'cycling': _preset('Cycling', 'Sitting & equipment', 'Hands forward on bars with pedals at different heights.',
                       _sides(left={'hip': [75, 0, 0], 'knee': -110}, right={'hip': [105, 0, 0], 'knee': -55},
                              lumbar_flex=[28, 0, 0], thoracic_flex=[10, 0, 0],
                              **_both(shoulder=[85, 0, 0], elbow=25))),
    'crouching': _preset('Crouching', 'Low & floor', 'Bent forward in a compact low squat.',
                         {'lumbar_flex': [30, 0, 0], **_both(hip=[100, 0, 0], knee=-125, ankle=[25, 0, 0])}),
    'deep-squat': _preset('Deep squat', 'Low & floor', 'Hips low between the knees, arms forward for balance.',
                          {**_both(hip=[120, 0, 0], knee=-145, ankle=[25, 0, 0], shoulder=[65, 0, 0]),
                           'lumbar_flex': [12, 0, 0]}, ground=True),
    'kneeling': _preset('Kneeling', 'Low & floor', 'Both knees folded beneath an upright torso.',
                        _both(hip=[15, 0, 0], knee=-145, ankle=[-20, 0, 0]), ground=True),
    'one-knee': _preset('One knee down', 'Low & floor', 'Left knee raised while the right knee rests low.',
                        _sides(left={'hip': [80, 0, 0], 'knee': -95},
                               right={'hip': [15, 0, 0], 'knee': -140}), ground=True),
    'crawling': _preset('Crawling on all fours', 'Low & floor', 'Hands and knees beneath a forward-leaning trunk.',
                        _both(hip=[75, 0, 0], knee=-115, shoulder=[95, 0, 0], elbow=85),
                        root_rotation_deg=[-90, 0, 0], ground=True),
    'supine': _preset('Lying on back', 'Low & floor', 'Face upward with arms beside the body and legs extended.',
                      root_rotation_deg=[90, 0, 0], ground=True),
    'prone': _preset('Lying face down', 'Low & floor', 'Face downward with arms beside the body and legs extended.',
                     root_rotation_deg=[-90, 0, 0], ground=True),
    'side-sleep': _preset('Sleeping on side', 'Low & floor', 'Side-lying with hips and knees gently folded.',
                          _both(hip=[65, 0, 0], knee=-85, shoulder=[75, 0, 0], elbow=70),
                          root_rotation_deg=[0, 90, 0], ground=True),
    'fetal': _preset('Fetal curl', 'Low & floor', 'Side-lying with thighs, knees and arms tucked toward the torso.',
                      {**_both(hip=[115, 0, 0], knee=-135, shoulder=[100, 0, 0], elbow=120),
                       'lumbar_flex': [35, 0, 0], 'thoracic_flex': [20, 0, 0]},
                      root_rotation_deg=[0, 90, 0], ground=True),
    'snow-angel': _preset('Snow angel', 'Low & floor', 'Face upward with arms and legs spread across the ground.',
                          _sides(left={'shoulder': [0, 0, -75], 'hip': [0, 30, 0]},
                                 right={'shoulder': [0, 0, 75], 'hip': [0, -30, 0]}),
                          root_rotation_deg=[90, 0, 0], ground=True),
    'pull-up': _preset('Pull-up', 'Sport & stretches', 'Elbows bent at an overhead bar; feet slightly folded.',
                       _both(shoulder=[80, 0, 0], elbow=135, wrist=[-35, 0, 0], hip=[4, 0, 0], knee=-8, ankle=[4, 0, 0])),
    'overhead-stretch': _preset('Overhead stretch', 'Sport & stretches', 'Both arms long overhead with a slight backward arch.',
                                {**_both(shoulder=[175, 0, 0]), 'lumbar_flex': [-15, 0, 0]}),
    'side-stretch': _preset('Side stretch', 'Sport & stretches', 'Right arm overhead while the torso bends to the left.',
                            _sides(left={'shoulder': [35, 0, -50]}, right={'shoulder': [170, 0, 0]},
                                   lumbar_flex=[0, 0, -20], thoracic_flex=[0, 0, -20])),
    'forward-fold': _preset('Standing forward fold', 'Sport & stretches', 'Torso bent over the thighs with arms hanging down.',
                             {**_both(hip=[45, 0, 0], knee=-12, shoulder=[-25, 0, 0]),
                              'lumbar_flex': [45, 0, 0], 'thoracic_flex': [30, 0, 0]}),
    'quad-stretch': _preset('Standing quad stretch', 'Sport & stretches', 'Right knee folded behind, left arm out for balance.',
                            _sides(left={'shoulder': [70, 0, -30]}, right={'hip': [-20, 0, 0], 'knee': -135,
                                                                          'shoulder': [-35, 0, 0], 'elbow': 110})),
    'swimmer-glide': _preset('Swimming · glide', 'Sport & stretches', 'Horizontal, face down with straight arms overhead.',
                             _both(shoulder=[175, 0, 0]), root_rotation_deg=[-90, 0, 0], ground=True),
    'swimming-stroke': _preset('Swimming · freestyle', 'Sport & stretches', 'Horizontal freestyle moment with one arm forward and one pulling.',
                               _sides(left={'shoulder': [170, 0, 0], 'hip': [12, 0, 0]},
                                      right={'shoulder': [45, 0, 0], 'elbow': 105, 'hip': [-15, 0, 0], 'knee': -20},
                                      neck_head=[0, 0, 25]), root_rotation_deg=[-90, 0, 0], ground=True),
    'diving': _preset('Diving forward', 'Sport & stretches', 'Arms reaching ahead, body inclined toward the water.',
                      _both(shoulder=[175, 0, 0], hip=[15, 0, 0], knee=-10),
                      root_rotation_deg=[-65, 0, 0], ground=True),
}
